### ISSUE TITLE
Retour depuis le résumé de commande ne garde pas toute la commande

### ISSUE THREAD

**Issue by karouf** [pakkumannn/chopsub#21]
Quanb on clique sur "Retour" sur l'écran de résumé de commande, on revient bien sur le formulaire de saisie de commande mais celui-ci ne conserve pas toutes les informations fournies auparavant : pain, taille, viande, fromage et température sont OK mais les légumes et la sauce ne sont pas conservés.

**Comment by pakkumannn** [comment]
soldé
