### ISSUE TITLE
Orthographe sur la page de vérification de commande

### ISSUE THREAD

**Issue by karouf** [pakkumannn/chopsub#30]
Il faudrait rajouter soit un point ".", soit deux points ":", soit une virgule ","
Et "ingrédient" prend un accent.
![image](https://cloud.githubusercontent.com/assets/2422/5296292/7da2519e-7ba2-11e4-8edc-741c41a6635d.png)

**Comment by pakkumannn** [comment]
Correction dans la branche master

**Comment by pakkumannn** [comment]
soldé
