### ISSUE TITLE
Orthographe sur la page de suppression de commande

### ISSUE THREAD

**Issue by karouf** [pakkumannn/chopsub#31]
Il faudrait rajouter soit un point ".", soit deux points ":", soit une virgule ","
Il y a "dndans" à la place de "dans".
![image](https://cloud.githubusercontent.com/assets/2422/5296326/cc2654c8-7ba2-11e4-8b38-c665dfbbd255.png)

**Comment by pakkumannn** [comment]
Modification dans la branche master

**Comment by pakkumannn** [comment]
soldé
